// Generated by cpp11: do not edit by hand
// clang-format off


#include "cpp11/declarations.hpp"
#include <R_ext/Visibility.h>

// maxima_call.cpp
void mx_boot_(std::string ecl_dir, std::string maxima_prefix, std::string maxima_userdir, std::string maxima_core_dir);
extern "C" SEXP _maxima_mx_boot_(SEXP ecl_dir, SEXP maxima_prefix, SEXP maxima_userdir, SEXP maxima_core_dir) {
  BEGIN_CPP11
    mx_boot_(cpp11::as_cpp<cpp11::decay_t<std::string>>(ecl_dir), cpp11::as_cpp<cpp11::decay_t<std::string>>(maxima_prefix), cpp11::as_cpp<cpp11::decay_t<std::string>>(maxima_userdir), cpp11::as_cpp<cpp11::decay_t<std::string>>(maxima_core_dir));
    return R_NilValue;
  END_CPP11
}
// maxima_call.cpp
void mx_shutdown_();
extern "C" SEXP _maxima_mx_shutdown_() {
  BEGIN_CPP11
    mx_shutdown_();
    return R_NilValue;
  END_CPP11
}
// maxima_call.cpp
bool mx_is_booted_();
extern "C" SEXP _maxima_mx_is_booted_() {
  BEGIN_CPP11
    return cpp11::as_sexp(mx_is_booted_());
  END_CPP11
}
// maxima_call.cpp
SEXP mx_from_double_(double x, bool is_integer);
extern "C" SEXP _maxima_mx_from_double_(SEXP x, SEXP is_integer) {
  BEGIN_CPP11
    return cpp11::as_sexp(mx_from_double_(cpp11::as_cpp<cpp11::decay_t<double>>(x), cpp11::as_cpp<cpp11::decay_t<bool>>(is_integer)));
  END_CPP11
}
// maxima_call.cpp
SEXP mx_symbol_(std::string name);
extern "C" SEXP _maxima_mx_symbol_(SEXP name) {
  BEGIN_CPP11
    return cpp11::as_sexp(mx_symbol_(cpp11::as_cpp<cpp11::decay_t<std::string>>(name)));
  END_CPP11
}
// maxima_call.cpp
SEXP mx_string_(std::string s);
extern "C" SEXP _maxima_mx_string_(SEXP s) {
  BEGIN_CPP11
    return cpp11::as_sexp(mx_string_(cpp11::as_cpp<cpp11::decay_t<std::string>>(s)));
  END_CPP11
}
// maxima_call.cpp
SEXP mx_call_(std::string name, cpp11::list args);
extern "C" SEXP _maxima_mx_call_(SEXP name, SEXP args) {
  BEGIN_CPP11
    return cpp11::as_sexp(mx_call_(cpp11::as_cpp<cpp11::decay_t<std::string>>(name), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(args)));
  END_CPP11
}
// maxima_call.cpp
SEXP mx_op_(std::string op, cpp11::list args);
extern "C" SEXP _maxima_mx_op_(SEXP op, SEXP args) {
  BEGIN_CPP11
    return cpp11::as_sexp(mx_op_(cpp11::as_cpp<cpp11::decay_t<std::string>>(op), cpp11::as_cpp<cpp11::decay_t<cpp11::list>>(args)));
  END_CPP11
}
// maxima_call.cpp
std::string mx_to_string_(SEXP x);
extern "C" SEXP _maxima_mx_to_string_(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(mx_to_string_(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// maxima_call.cpp
SEXP mx_to_r_expr_(SEXP x);
extern "C" SEXP _maxima_mx_to_r_expr_(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(mx_to_r_expr_(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}
// maxima_call.cpp
double mx_to_double_(SEXP x);
extern "C" SEXP _maxima_mx_to_double_(SEXP x) {
  BEGIN_CPP11
    return cpp11::as_sexp(mx_to_double_(cpp11::as_cpp<cpp11::decay_t<SEXP>>(x)));
  END_CPP11
}

extern "C" {
static const R_CallMethodDef CallEntries[] = {
    {"_maxima_mx_boot_",        (DL_FUNC) &_maxima_mx_boot_,        4},
    {"_maxima_mx_call_",        (DL_FUNC) &_maxima_mx_call_,        2},
    {"_maxima_mx_from_double_", (DL_FUNC) &_maxima_mx_from_double_, 2},
    {"_maxima_mx_is_booted_",   (DL_FUNC) &_maxima_mx_is_booted_,   0},
    {"_maxima_mx_op_",          (DL_FUNC) &_maxima_mx_op_,          2},
    {"_maxima_mx_shutdown_",    (DL_FUNC) &_maxima_mx_shutdown_,    0},
    {"_maxima_mx_string_",      (DL_FUNC) &_maxima_mx_string_,      1},
    {"_maxima_mx_symbol_",      (DL_FUNC) &_maxima_mx_symbol_,      1},
    {"_maxima_mx_to_double_",   (DL_FUNC) &_maxima_mx_to_double_,   1},
    {"_maxima_mx_to_r_expr_",   (DL_FUNC) &_maxima_mx_to_r_expr_,   1},
    {"_maxima_mx_to_string_",   (DL_FUNC) &_maxima_mx_to_string_,   1},
    {NULL, NULL, 0}
};
}

extern "C" attribute_visible void R_init_maxima(DllInfo* dll){
  R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
  R_useDynamicSymbols(dll, FALSE);
  R_forceSymbols(dll, TRUE);
}
