# Generated by cpp11: do not edit by hand

mx_boot_ <- function(ecl_dir, maxima_prefix, maxima_userdir, maxima_core_dir) {
  invisible(.Call(`_maxima_mx_boot_`, ecl_dir, maxima_prefix, maxima_userdir, maxima_core_dir))
}

mx_shutdown_ <- function() {
  invisible(.Call(`_maxima_mx_shutdown_`))
}

mx_is_booted_ <- function() {
  .Call(`_maxima_mx_is_booted_`)
}

mx_from_double_ <- function(x, is_integer) {
  .Call(`_maxima_mx_from_double_`, x, is_integer)
}

mx_symbol_ <- function(name) {
  .Call(`_maxima_mx_symbol_`, name)
}

mx_string_ <- function(s) {
  .Call(`_maxima_mx_string_`, s)
}

mx_call_ <- function(name, args) {
  .Call(`_maxima_mx_call_`, name, args)
}

mx_op_ <- function(op, args) {
  .Call(`_maxima_mx_op_`, op, args)
}

mx_to_string_ <- function(x) {
  .Call(`_maxima_mx_to_string_`, x)
}

mx_to_r_expr_ <- function(x) {
  .Call(`_maxima_mx_to_r_expr_`, x)
}

mx_to_double_ <- function(x) {
  .Call(`_maxima_mx_to_double_`, x)
}
